"""Initial migration

Revision ID: 6526a5a2aef1
Revises: 742ed5bdced8
Create Date: 2025-06-24 22:29:36.886311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6526a5a2aef1'
down_revision = '742ed5bdced8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audio_notifications', sa.Boolean(), nullable=True),
    sa.Column('visual_notifications', sa.Boolean(), nullable=True),
    sa.Column('browser_notifications', sa.Boolean(), nullable=True),
    sa.Column('audio_volume', sa.Float(), nullable=True),
    sa.Column('audio_enabled', sa.Boolean(), nullable=True),
    sa.Column('referral_notifications', sa.Boolean(), nullable=True),
    sa.Column('bed_status_notifications', sa.Boolean(), nullable=True),
    sa.Column('system_notifications', sa.Boolean(), nullable=True),
    sa.Column('notification_duration', sa.Integer(), nullable=True),
    sa.Column('auto_escalate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
