"""Initial migration

Revision ID: 17088e67d6a0
Revises: 5353d8676f38
Create Date: 2025-06-22 18:32:28.145785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17088e67d6a0'
down_revision = '5353d8676f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_requests', schema=None) as batch_op:
        batch_op.drop_column('patient_name')

    # ### end Alembic commands ###
