"""Initial migration

Revision ID: 5353d8676f38
Revises: c0e27a36525d
Create Date: 2025-06-22 18:31:53.446785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5353d8676f38'
down_revision = 'c0e27a36525d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_requests', schema=None) as batch_op:
        batch_op.drop_column('current_treatment')
        batch_op.drop_column('primary_diagnosis')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_diagnosis', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_treatment', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
