"""Initial migration

Revision ID: 7d68523d12b1
Revises: a1603f9830e5
Create Date: 2025-06-21 13:33:18.201836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d68523d12b1'
down_revision = 'a1603f9830e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=20), nullable=True),
    sa.Column('avg_response_time', sa.Float(), nullable=True),
    sa.Column('last_response_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requesting_hospital_id', sa.Integer(), nullable=False),
    sa.Column('target_hospital_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_gender', sa.String(length=10), nullable=True),
    sa.Column('reason_for_referral', sa.Text(), nullable=False),
    sa.Column('urgency_level', sa.String(length=20), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('contact_method', sa.String(length=20), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['requesting_hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['target_hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_request_id', sa.Integer(), nullable=False),
    sa.Column('responding_hospital_id', sa.Integer(), nullable=False),
    sa.Column('response_type', sa.String(length=20), nullable=False),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('available_beds', sa.Integer(), nullable=True),
    sa.Column('estimated_arrival_time', sa.String(length=50), nullable=True),
    sa.Column('responder_name', sa.String(length=100), nullable=True),
    sa.Column('responder_phone', sa.String(length=20), nullable=True),
    sa.Column('responder_email', sa.String(length=120), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referral_request_id'], ['referral_requests.id'], ),
    sa.ForeignKeyConstraint(['responding_hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral_responses')
    op.drop_table('referral_requests')
    op.drop_table('hospital_contacts')
    # ### end Alembic commands ###
