"""Initial migration

Revision ID: 8678e4ddeb04
Revises: 7d68523d12b1
Create Date: 2025-06-22 16:32:33.257819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8678e4ddeb04'
down_revision = '7d68523d12b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_requests', schema=None) as batch_op:
        batch_op.drop_column('patient_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
