"""Initial migration

Revision ID: c0e27a36525d
Revises: 8678e4ddeb04
Create Date: 2025-06-22 17:07:23.679563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e27a36525d'
down_revision = '8678e4ddeb04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_diagnosis', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('current_treatment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_requests', schema=None) as batch_op:
        batch_op.drop_column('current_treatment')
        batch_op.drop_column('primary_diagnosis')

    # ### end Alembic commands ###
