"""Initial migration

Revision ID: 0a6a680f3d3b
Revises: 53ecb50f1f93
Create Date: 2025-06-09 12:44:17.839593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6a680f3d3b'
down_revision = '53ecb50f1f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
