"""Initial migration

Revision ID: 401d7ab81c80
Revises: 48483955749c
Create Date: 2025-07-10 17:05:00.758291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401d7ab81c80'
down_revision = '48483955749c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('verification_code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('notification_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('verification_code')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('privilege_level', sa.String(length=20), nullable=True),
    sa.Column('verification_docs', sa.String(length=200), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('beds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('bed_number', sa.Integer(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('bed_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'bed_number', name='_hospital_bed_uc')
    )
    op.create_table('discharges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('bed_number', sa.Integer(), nullable=False),
    sa.Column('admission_time', sa.DateTime(), nullable=False),
    sa.Column('discharge_time', sa.DateTime(), nullable=True),
    sa.Column('discharging_doctor', sa.String(length=100), nullable=False),
    sa.Column('discharge_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=20), nullable=True),
    sa.Column('avg_response_time', sa.Float(), nullable=True),
    sa.Column('last_response_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('doctor', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('admission_time', sa.DateTime(), nullable=True),
    sa.Column('discharge_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('referral_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requesting_hospital_id', sa.Integer(), nullable=False),
    sa.Column('target_hospital_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_gender', sa.String(length=10), nullable=True),
    sa.Column('reason_for_referral', sa.Text(), nullable=False),
    sa.Column('urgency_level', sa.String(length=20), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('primary_diagnosis', sa.String(length=255), nullable=True),
    sa.Column('current_treatment', sa.Text(), nullable=True),
    sa.Column('contact_method', sa.String(length=20), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['requesting_hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['target_hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audio_notifications', sa.Boolean(), nullable=True),
    sa.Column('visual_notifications', sa.Boolean(), nullable=True),
    sa.Column('browser_notifications', sa.Boolean(), nullable=True),
    sa.Column('audio_volume', sa.Float(), nullable=True),
    sa.Column('audio_enabled', sa.Boolean(), nullable=True),
    sa.Column('referral_notifications', sa.Boolean(), nullable=True),
    sa.Column('bed_status_notifications', sa.Boolean(), nullable=True),
    sa.Column('system_notifications', sa.Boolean(), nullable=True),
    sa.Column('notification_duration', sa.Integer(), nullable=True),
    sa.Column('auto_escalate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('patient_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_request_id', sa.Integer(), nullable=False),
    sa.Column('from_hospital_id', sa.Integer(), nullable=False),
    sa.Column('to_hospital_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_gender', sa.String(length=10), nullable=True),
    sa.Column('primary_diagnosis', sa.String(length=255), nullable=True),
    sa.Column('urgency_level', sa.String(length=20), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('transfer_initiated_at', sa.DateTime(), nullable=True),
    sa.Column('en_route_at', sa.DateTime(), nullable=True),
    sa.Column('admitted_at', sa.DateTime(), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('transfer_notes', sa.Text(), nullable=True),
    sa.Column('arrival_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['referral_request_id'], ['referral_requests.id'], ),
    sa.ForeignKeyConstraint(['to_hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_request_id', sa.Integer(), nullable=False),
    sa.Column('responding_hospital_id', sa.Integer(), nullable=False),
    sa.Column('response_type', sa.String(length=20), nullable=False),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('available_beds', sa.Integer(), nullable=True),
    sa.Column('estimated_arrival_time', sa.String(length=50), nullable=True),
    sa.Column('responder_name', sa.String(length=100), nullable=True),
    sa.Column('responder_phone', sa.String(length=20), nullable=True),
    sa.Column('responder_email', sa.String(length=120), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referral_request_id'], ['referral_requests.id'], ),
    sa.ForeignKeyConstraint(['responding_hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral_responses')
    op.drop_table('patient_transfers')
    op.drop_table('user_settings')
    op.drop_table('referral_requests')
    op.drop_table('users')
    op.drop_table('admissions')
    op.drop_table('hospital_contacts')
    op.drop_table('discharges')
    op.drop_table('beds')
    op.drop_table('admins')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
