"""Initial migration

Revision ID: 48483955749c
Revises: f7ea7cfeab7f
Create Date: 2025-07-10 15:18:57.694843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48483955749c'
down_revision = 'f7ea7cfeab7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
