"""Initial migration

Revision ID: 528cf676a470
Revises: 6c933a6c1dc4
Create Date: 2025-07-14 15:29:47.802120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528cf676a470'
down_revision = '6c933a6c1dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_transfers', schema=None) as batch_op:
        batch_op.create_index('idx_transfer_created_at', ['transfer_initiated_at'], unique=False)
        batch_op.create_index('idx_transfer_hospitals', ['from_hospital_id', 'to_hospital_id'], unique=False)
        batch_op.create_index('idx_transfer_status', ['status'], unique=False)

    with op.batch_alter_table('referral_requests', schema=None) as batch_op:
        batch_op.create_index('idx_referral_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_referral_hospitals', ['requesting_hospital_id', 'target_hospital_id'], unique=False)
        batch_op.create_index('idx_referral_status', ['status'], unique=False)
        batch_op.create_index('idx_referral_urgency', ['urgency_level'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_referral_urgency')
        batch_op.drop_index('idx_referral_status')
        batch_op.drop_index('idx_referral_hospitals')
        batch_op.drop_index('idx_referral_created_at')

    with op.batch_alter_table('patient_transfers', schema=None) as batch_op:
        batch_op.drop_index('idx_transfer_status')
        batch_op.drop_index('idx_transfer_hospitals')
        batch_op.drop_index('idx_transfer_created_at')

    # ### end Alembic commands ###
