"""Initial migration

Revision ID: 53ecb50f1f93
Revises: b183cd53691a
Create Date: 2025-06-09 12:43:59.375674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ecb50f1f93'
down_revision = 'b183cd53691a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
