"""Add ICU beds columns to Hospital

Revision ID: 93ff01d367f6
Revises: 
Create Date: 2025-05-28 19:36:27.148802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ff01d367f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_icu_beds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('available_icu_beds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_column('available_icu_beds')
        batch_op.drop_column('total_icu_beds')

    # ### end Alembic commands ###
