"""Initial migration

Revision ID: f7ea7cfeab7f
Revises: 
Create Date: 2025-07-10 00:47:16.158786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ea7cfeab7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=128), nullable=True))

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_token')
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_column('is_test')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('reset_token')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
