"""Initial migration

Revision ID: fe509774f4f3
Revises: 6526a5a2aef1
Create Date: 2025-06-25 00:41:32.307560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe509774f4f3'
down_revision = '6526a5a2aef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_request_id', sa.Integer(), nullable=False),
    sa.Column('from_hospital_id', sa.Integer(), nullable=False),
    sa.Column('to_hospital_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_gender', sa.String(length=10), nullable=True),
    sa.Column('primary_diagnosis', sa.String(length=255), nullable=True),
    sa.Column('urgency_level', sa.String(length=20), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('transfer_initiated_at', sa.DateTime(), nullable=True),
    sa.Column('en_route_at', sa.DateTime(), nullable=True),
    sa.Column('admitted_at', sa.DateTime(), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('transfer_notes', sa.Text(), nullable=True),
    sa.Column('arrival_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['referral_request_id'], ['referral_requests.id'], ),
    sa.ForeignKeyConstraint(['to_hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_transfers')
    # ### end Alembic commands ###
